export const roomData2 = 
    {
        "habitaciones": [
          {
            "ID_habitacion": 1,
            "name": 'Superior Room',
            "tipo_habitacion": "Ordinaria",
            "camas_disponibles": 1,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 100.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/OIP.3r6tmFYqMGnVhLEbRbelbwHaE8?pid=ImgDet&rs=1",
            "descripcion": "Habitación confortable con una cama individual."
          },
          {
            "ID_habitacion": 2,
            "name": 'Signature Room',
            "tipo_habitacion": "Ordinaria",
            "camas_disponibles": 1,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 100.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/OIP.3r6tmFYqMGnVhLEbRbelbwHaE8?pid=ImgDet&rs=1",
            "descripcion": "Habitación confortable con una cama individual."
          },
          {
            "ID_habitacion": 3,
            "name": 'Deluxe Room',
            "tipo_habitacion": "Ordinaria",
            "camas_disponibles": 1,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 100.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/OIP.3r6tmFYqMGnVhLEbRbelbwHaE8?pid=ImgDet&rs=1",
            "descripcion": "Habitación confortable con una cama individual."
          },
         
          {
            "ID_habitacion": 10,
            "tipo_habitacion": "Ordinaria",
            "camas_disponibles": 1,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 100.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/OIP.3r6tmFYqMGnVhLEbRbelbwHaE8?pid=ImgDet&rs=1",
            "descripcion": "Habitación confortable con una cama individual."
          },
      
          {
            "ID_habitacion": 22,
            "tipo_habitacion": "Ordinaria Doble",
            "camas_disponibles": 1,
            "tipo_cama": "Doble King",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 150.00,
            "size": 48,
            "imagen": "https://i.pinimg.com/originals/43/02/60/430260fdfeb2eb3d1c89c18823a97ed4.jpg",
            "descripcion": "Habitación amplia con una cama doble king size."
          },
          {
            "ID_habitacion": 23,
            "tipo_habitacion": "Ordinaria Doble",
            "camas_disponibles": 1,
            "tipo_cama": "Doble King",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 150.00,
            "size": 48,
            "imagen": "https://i.pinimg.com/originals/43/02/60/430260fdfeb2eb3d1c89c18823a97ed4.jpg",
            "descripcion": "Habitación amplia con una cama doble king size."
          },
          {
            "ID_habitacion": 24,
            "tipo_habitacion": "Ordinaria Doble",
            "camas_disponibles": 1,
            "tipo_cama": "Doble King",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 150.00,
            "size": 48,
            "imagen": "https://i.pinimg.com/originals/43/02/60/430260fdfeb2eb3d1c89c18823a97ed4.jpg",
            "descripcion": "Habitación amplia con una cama doble king size."
          },
          {
            "ID_habitacion": 25,
            "tipo_habitacion": "Ordinaria Doble",
            "camas_disponibles": 1,
            "tipo_cama": "Doble King",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 150.00,
            "size": 48,
            "imagen": "https://i.pinimg.com/originals/43/02/60/430260fdfeb2eb3d1c89c18823a97ed4.jpg",
            "descripcion": "Habitación amplia con una cama doble king size."
          },
        
       
          {
            "ID_habitacion": 31,
            "name": 'Luxury Suite Room',
            "tipo_habitacion": "Compartida",
            "camas_disponibles": 3,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 50.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/R.94162cc78b7d3b683aabcca421387d00?rik=7CTQhEYBhwP9VA&riu=http%3a%2f%2fwww.hotel-city47.com%2fwp-content%2fblogs.dir%2f864%2ffiles%2ftripleslider%2fHotel_city_habitacion_triple_01.jpg&ehk=ibC5N%2fXIiNM%2bWo270YvartDmzCULJWYnNw14vifgUdM%3d&risl=&pid=ImgRaw&r=0",
            "descripcion": "Habitación compartida con 3 camas sencillas."
          },
          {
            "ID_habitacion": 32,
            "tipo_habitacion": "Compartida",
            "camas_disponibles": 3,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 50.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/R.94162cc78b7d3b683aabcca421387d00?rik=7CTQhEYBhwP9VA&riu=http%3a%2f%2fwww.hotel-city47.com%2fwp-content%2fblogs.dir%2f864%2ffiles%2ftripleslider%2fHotel_city_habitacion_triple_01.jpg&ehk=ibC5N%2fXIiNM%2bWo270YvartDmzCULJWYnNw14vifgUdM%3d&risl=&pid=ImgRaw&r=0",
            "descripcion": "Habitación compartida con 3 camas sencillas."
          },
          {
            "ID_habitacion": 40,
            "tipo_habitacion": "Compartida",
            "camas_disponibles": 3,
            "tipo_cama": "Sencilla",
            "facilities": [
              { "name": 'Wifi'},
              { "name": 'Coffee'},
              { "name": 'Bath'},
              { "name": 'Parking Space'},
              { "name": 'Swimming Pool'},
              { "name": 'Breakfast'},
              { "name": 'GYM'  },
              { "name": 'Drinks'},
            ],
            "precio": 50.00,
            "size": 48,
            "imagen": "https://th.bing.com/th/id/R.94162cc78b7d3b683aabcca421387d00?rik=7CTQhEYBhwP9VA&riu=http%3a%2f%2fwww.hotel-city47.com%2fwp-content%2fblogs.dir%2f864%2ffiles%2ftripleslider%2fHotel_city_habitacion_triple_01.jpg&ehk=ibC5N%2fXIiNM%2bWo270YvartDmzCULJWYnNw14vifgUdM%3d&risl=&pid=ImgRaw&r=0",
            "descripcion": "Habitación compartida con 3 camas sencillas."
          }
        ]
      }
